# Generated by Django 2.1.2 on 2018-10-21 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnerability', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('date_released', models.DateField()),
                ('date_applied', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birth_date', models.DateField(null=True)),
                ('position', models.CharField(default='', max_length=50)),
                ('languages', models.ManyToManyField(to='bugtracker.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('level', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('attachment', models.FileField(upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bugtracker.Profile')),
                ('bugs', models.ManyToManyField(to='bugtracker.Bug')),
                ('duplicate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bugtracker.Ticket')),
                ('expert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_under_supervision', to='bugtracker.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='patch',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bugtracker.Profile'),
        ),
        migrations.AddField(
            model_name='module',
            name='expert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bugtracker.Profile'),
        ),
        migrations.AddField(
            model_name='module',
            name='languages',
            field=models.ManyToManyField(to='bugtracker.Language'),
        ),
        migrations.AddField(
            model_name='bug',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bugtracker.Module'),
        ),
        migrations.AddField(
            model_name='bug',
            name='patch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bugtracker.Patch'),
        ),
        migrations.AddField(
            model_name='bug',
            name='severity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bugtracker.Severity'),
        ),
    ]
