# Generated by Django 2.1.2 on 2018-10-20 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnerability', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='module',
            old_name='person',
            new_name='expert',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_programmer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='module',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='patch',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='reward',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='vulnerability',
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='expert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_under_supervision', to='bugtracker.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bug',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bugtracker.Module'),
        ),
        migrations.AddField(
            model_name='bug',
            name='patch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bugtracker.Patch'),
        ),
        migrations.AddField(
            model_name='bug',
            name='severity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bugtracker.Severity'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='bugs',
            field=models.ManyToManyField(to='bugtracker.Bug'),
        ),
    ]
