# Generated by Django 2.1.2 on 2018-10-27 08:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0002_auto_20181022_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
