# Generated by Django 2.1.2 on 2018-11-13 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0004_auto_20181105_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bugs', to='bugtracker.Module'),
        ),
        migrations.AlterField(
            model_name='patch',
            name='status',
            field=models.CharField(choices=[('applied', 'applied'), ('approved', 'approved'), ('in development', 'in development')], default='in development', max_length=20),
        ),
    ]
