# Generated by Django 2.1.2 on 2018-11-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0005_auto_20181113_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='bugs',
            field=models.ManyToManyField(related_name='tickets', to='bugtracker.Bug'),
        ),
    ]
