# Generated by Django 2.1.2 on 2018-11-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0006_auto_20181120_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed'), ('feedback', 'feedback'), ('duplicate', 'duplicate')], default='open', max_length=20),
        ),
    ]
