# Generated by Django 2.1.2 on 2018-11-23 16:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0007_auto_20181120_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='patch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bugs', to='bugtracker.Patch'),
        ),
        migrations.AlterField(
            model_name='patch',
            name='date_released',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patch',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('hotfix', 'hotfix'), ('complete', 'complete')], max_length=20),
        ),
    ]
