# Generated by Django 2.1.2 on 2018-11-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0009_auto_20181123_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('closed', 'closed'), ('assigned', 'assigned'), ('duplicate', 'duplicate')], default='new', max_length=20),
        ),
    ]
