# Generated by Django 2.1.2 on 2018-11-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0011_auto_20181124_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='vulnerability',
            field=models.BooleanField(default=False),
        ),
    ]
