# Generated by Django 2.1.2 on 2018-11-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0012_auto_20181124_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='severity',
            name='color',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
