# Generated by Django 2.1.2 on 2018-11-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0013_severity_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(upload_to='tickets/%Y/%m/%d'),
        ),
    ]
