# Generated by Django 2.1.2 on 2018-12-01 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0014_auto_20181125_0751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_type',
            new_name='position',
        ),
    ]
