# Generated by Django 2.1.2 on 2018-12-01 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0015_auto_20181201_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patch',
            name='date_applied',
        ),
        migrations.AddField(
            model_name='patch',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patch',
            name='name',
            field=models.CharField(default='Patch', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patch',
            name='date_released',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='patch',
            name='status',
            field=models.CharField(choices=[('in progress', 'in progress'), ('awaiting approval', 'awaiting approval'), ('approved', 'approved'), ('released', 'released')], default='in progress', max_length=20),
        ),
    ]
