# Generated by Django 2.1.2 on 2018-12-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0016_auto_20181201_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reward',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
